baseURL = "http://example.org/"
languageCode = "ru-ru"
theme = "hugo-theme-yuminos"

paginate = 50
DefaultContentLanguage = "ru"
enableInlineShortcodes = true
enableRobotsTXT = false
enableEmoji = true

ignoreErrors = ["error-remote-getjson"]

title = "YU0DEV"

[params]
  customTitle = true
  yandexMetrikaId = "96278937"
  description = "Личный блог. Статьи про IT и не только."
  keywords = ["блог", "статьи", "программирование", "IT", "туториалы"]
  color = "light"
  monoDarkIcon = true
  katex = true
  relatedMax = 5
  thinkpadKbd = true
  startTime = "2023-08-24T10:00:00"
  [params.author]
    name = "Lev Yuvenskiy"
  [params.comments]
    enabled = true
  [params.comments.giscus]
      repo = "Yu-Leo/yu0dev"
      repoID = "R_kgDOKLBKuQ"
      category = "Announcements"
      categoryID = "DIC_kwDOKLBKuc4Ccu-K"
      mapping = "title"
      reactionsEnabled = 1
      emitMetadata = 0
      lazy = false
      lang = "en"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = "keywords"
    weight = 30
  [[related.indices]]
    name = "tags"
    weight = 50
  [[related.indices]]
    name = "categories"
    weight = 50
  [[related.indices]]
    name = "date"
    weight = 40
    
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      highlight = true
  [markup.highlight]
    tabWidth = 4
    lineNumbersInTable=false
    noClasses=false   
    
[menu]
  [[menu.main]]
    identifier = "github"
    name = "github"
    url = "https://github.com/Yu-Leo"
    weight = 20
  [[menu.main]]
    identifier = "tg"
    name = "telegram"
    url = "https://t.me/YU0DEV"
    weight = 30
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/posts/"
    weight = 5

[taxonomies]
  category = "categories"
  tag = "tags"

[privacy]
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

