baseURL = 'http://example.org/'
languageCode = 'ru-ru'
theme = 'hugo-theme-yuminos'

paginate = 50
DefaultContentLanguage = "ru"
enableInlineShortcodes = true

ignoreErrors = ["error-remote-getjson"]

title = "YU0DEV"

enableEmoji = true

[params]
  color = 'light'
  monoDarkIcon = true
  katex = true
  relatedMax = 5
  thinkpadKbd = true
  [params.runTime]
    enabled = true
    startTime = "2023-08-24T20:00:00"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = 'keywords'
    weight = 30
  [[related.indices]]
    name = 'tags'
    weight = 50
  [[related.indices]]
    name = 'categories'
    weight = 50
  [[related.indices]]
    name = 'date'
    weight = 40
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'gruvbox'
    tabWidth = 4
    
[menu]
  [[menu.main]]
    identifier = "github"
    name = "github"
    url = "https://github.com/Yu-Leo"
    weight = 20
  [[menu.main]]
    identifier = "tg"
    name = "telegram"
    url = "https://t.me/YU0DEV"
    weight = 30
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "books"
    name = "books"
    url = "/books/"
    weight = 5
    
[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  categories = "/:slug/"

[privacy]
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

